{% set name = "google-cloud-bigquery-datatransfer" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-bigquery-datatransfer-{{ version }}.tar.gz
  sha256: 4d1e357e7fdee35f39456f3391ddd263513f8cd419b94609af59fe4f034f1d3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.bigquery_datatransfer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-datatransfer
  summary: Google Cloud Bigquery Datatransfer API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "BigQuery Data Transfer API is a Google Cloud service that lets client applications transfer data from partner SaaS applications to Google BigQuery on a scheduled, managed basis.\nSee the [quick start guide](https://googleapis.dev/python/bigquerydatatransfer/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/bigquerydatatransfer/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-datatransfer

extra:
  recipe-maintainers:
    - parthea
    - xylar
